### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by Mrpeluca** [makestuff/libfpgalink#33]
My actual system is MacOs X 10.11.1.
When I try to build this (*) part Im getting this error(**).
(*)
cd $HOME/makestuff/apps
  ../scripts/msget.sh makestuff/lsep
  cd lsep
  make deps

(**)
clang: error: unsupported option '-gstabs+'
make[2]: *** [osx/dbg/.build/libusbwrap.o] Error 1
make[1]: *** [deps] Error 2
make: *** [/Users/nico/Documents/Especializacion_SE/DSP/makestuff/libs/libusbwrap/osx] Error 2

I have this prereqs. installed:
Xcode : Version 7.1.1 (7B1005)
wget: GNU Wget 1.17
libusb: libusb 1.0.20

I hope this info be enought to help me resolve this issue.
Regards

**Comment by makestuff** [comment]
This is because the `-gstabs+` option was removed from the Xcode compiler at some point (see for example [this thread](https://groups.google.com/d/msg/fpgalink-users/PO4eoEU-LUQ/USF2cgGxD2wJ). I "fixed" it by just removing the `-gstabs+` option from later releases (e.g 20150807). Unfortunately this means debug symbols will not be available in Xcode. Please try building again, like this:

    mkdir $HOME/20150807
    cd $HOME/20150807
    wget -qO- http://tiny.cc/msbil | tar zxf -```
    
    # Fetch and build lsep:
    cd makestuff/apps
    ../scripts/msget.sh makestuff/lsep/20150807
    cd lsep
    make deps

Lastly, in future please use the [mailing-list](https://groups.google.com/forum/#!forum/fpgalink-users) for problems of this kind.
